#pragma once
#include <Adafruit_TinyUSB.h>

// Report ID
enum {
  KEYBOARD = 1,
  MOUSE,
  GAMEPAD,
  GAMEPAD_BUTTON,
  GAMEPAD_HAT,
  GAMEPAD_AXIS,
  CONSUMER_CONTROL, // Media, volume etc ..
  
};

enum { 
  GAMEPAD_LEFT_STICK_X,
  GAMEPAD_LEFT_STICK_Y,
  GAMEPAD_LEFT_TRIGGER,
  GAMEPAD_RIGHT_STICK_X,
  GAMEPAD_RIGHT_STICK_Y,
  GAMEPAD_RIGHT_TRIGGER
};

//custom addition to match existing MOUSE_BUTTON_* enums
enum {
  MOUSE_SCROLL_UP     = TU_BIT(5),
  MOUSE_SCROLL_DOWN   = TU_BIT(6),
  MOUSE_SCROLL_LEFT   = TU_BIT(7),
  MOUSE_SCROLL_RIGHT  = TU_BIT(8),
  MOUSE_MOVE_UP       = TU_BIT(9),
  MOUSE_MOVE_DOWN     = TU_BIT(10),
  MOUSE_MOVE_LEFT     = TU_BIT(11),
  MOUSE_MOVE_RIGHT    = TU_BIT(12),
};